version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  rails:
    build:
      context: .
    volumes:
      - ./photobook_rails:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'

